name: tazawad
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^6.0.6

  # BASE

  sentry: ^7.12.0
  # FIREBASE PACKAGES
  #  firebase_crashlytics: ^3.4.3
  #  firebase_analytics: ^10.6.3
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_remote_config: ^4.3.3

  # UI
  flutter_vector_icons: ^2.0.0
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  otp_text_field: ^1.1.3
  flutter_staggered_grid_view: ^0.7.0
  country_code_picker: ^3.0.0
  html: ^0.15.4
  #  flutter_html: ^2.2.1
  flutter_widget_from_html: ^0.14.6
  package_info_plus: ^4.2.0
  clippy_flutter: 2.0.0-nullsafety.1

  # PUSH NOTIFICATION
  #  onesignal_flutter: ^5.0.3

  # STATE MANAGEMENT
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1

  # ADS
  #google_mobile_ads: ^3.1.0

  # VIDEOS
  video_player: ^2.8.1

  # IMAGES
  image_picker: ^1.0.4
  #  cached_network_image: ^3.2.3
  photo_view: ^0.14.0

  # AUTHENTICATION
  google_sign_in: ^6.1.6
  the_apple_sign_in: ^1.1.1

  # CONNECTIVITY
  http: ^1.1.0
  #  connectivity: ^3.0.6
  #  share: ^2.0.4

  #TOOLS
  google_fonts: ^6.1.0

  # WEB TOOLS
  #  webview_flutter: ^4.4.2

  # PAYMENTS
  #  flutter_stripe: ^9.5.0+1
  flutterwave_standard: ^1.0.8
  razorpay_flutter: ^1.3.5
  #  flutter_paystack: ^1.0.7
  #myfatoorah_flutter: ^3.0.4
  # moyasar:
  #   git:
  #     url: https://github.com/kururu-abdo/moyasar-flutter.git
  #     ref: kururu # branch name

  # LAUNCH URL
  url_launcher: ^6.2.1
  #UTIITY
  #  flutter_downloader: ^1.11.4
  # download_file: ^1.0.1
  otp_autofill: ^3.0.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  #  permission_handler: ^11.0.1
  #  device_info: ^2.0.3
  android_path_provider: ^0.3.0
  qr_flutter: ^4.1.0


dependency_overrides:
  flutter_layout_grid: ^2.0.5
  package_info_plus: ^4.2.0
  #  webview_flutter: ^3.0.4
  flutter_svg: ^2.0.9
  #  intl: 0.18.0


dev_dependencies:

  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"

  change_app_package_name: ^1.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/mightystore/
    - lang/
    - assets/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajwal/Tajawal-Bold.ttf
        - asset: assets/fonts/tajwal/Tajawal-Medium.ttf
        - asset: assets/fonts/tajwal/Tajawal-Regular.ttf
          weight: 500

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "images/mightystore/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  generate: true